{
 "title": "Evolução Cripto X Dólar X CDI",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Preco (R$) do Bitcoin / dia",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select data as time, cotacao_btc_real as \"Preço R$\"\r\nfrom historico_cotacoes_btc hcb \r\norder by data desc\r\n--limit 90"
    }
   ]
  },
  {
   "title": "PREÇO (R$) MÉDIO DO BITCOIN / MÊS",
   "type": "table",
   "description": "EVOLUÇÃO HISTÓRICA MÊS A MÊS DO PREÇO (R$) DO BITCOIN",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  concat_ws('-',LPAD(DATA_MES::text, 2, '0'), DATA_ANO) AS \"MES-ANO\",\r\n  AVG(cotacao_btc_real) AS \"R$ MÉDIO\"\r\nFROM historico_cotacoes_btc \r\nGROUP BY data_mes, data_ano \r\nORDER BY data_ano desc, data_mes desc\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "SÉRIE DO DOLAR COMERCIAL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "select data as time, cotacao_dolar as \"Cotação Dolar Comercial\"\r\nfrom historico_cotacoes_btc hcb\r\norder by data"
    }
   ]
  },
  {
   "title": "SÉRIE HISTÓRICA DO CDI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select data as time, cdi as \"CDI\"\r\nfrom historico_cdi hc"
    }
   ]
  }
 ]
}